addons:
  apt:
    packages:
      - g++-5
      - unicode-data
    sources:
      - ubuntu-toolchain-r-test

before_script:
  - npm i -g eslint
  - eslint .

env:
  - CXX=g++-5

language: node_js

node_js:
  - 4
  - 6
  - 7

sudo: false
